-- Supabase schema for cdj-app
-- Run in Supabase SQL editor. Adjust schema name if needed.

-- persons
create table if not exists public.persons (
  id bigint generated by default as identity primary key,
  name text not null,
  alias text null,
  birthdate text null,
  email text null,
  photo text null,
  password_hash text null,
  inserted_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create index if not exists persons_email_idx on public.persons (lower(email));
create index if not exists persons_name_idx on public.persons (lower(name));

-- events
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text null,
  location text null,
  locationId bigint null,
  asadorId bigint null,
  date text not null,
  attendeeCount integer not null default 0,
  totalFoodCost double precision not null default 0,
  totalDrinkCost double precision not null default 0,
  photo text null,
  inserted_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
create index if not exists events_date_idx on public.events (date desc);

-- eventDetails
create table if not exists public.eventDetails (
  id bigint generated by default as identity primary key,
  eventId bigint not null references public.events(id) on delete cascade,
  personId bigint not null references public.persons(id) on delete cascade,
  includeFood boolean null,
  includeDrink boolean null,
  foodCost double precision null,
  drinkCost double precision null,
  note text null,
  inserted_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
create index if not exists eventDetails_event_idx on public.eventDetails (eventId);
create index if not exists eventDetails_person_idx on public.eventDetails (personId);

-- locations
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null,
  address text null,
  maps_url text null,
  inserted_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
create index if not exists locations_name_idx on public.locations (lower(name));

-- Row Level Security (optional: enable and add policies)
-- alter table public.persons enable row level security;
-- alter table public.events enable row level security;
-- alter table public.eventDetails enable row level security;
-- alter table public.locations enable row level security;

-- Basic open policies (adjust for your needs; this allows anon read/write)
-- create policy "anon_select_persons" on public.persons for select using (true);
-- create policy "anon_insert_persons" on public.persons for insert with check (true);
-- create policy "anon_update_persons" on public.persons for update using (true);
-- create policy "anon_delete_persons" on public.persons for delete using (true);

-- Repeat policies for other tables as needed.
